# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import datetime
version = '3.3.0.dev'
plugins = [
{'plugintype': 'channel', 'apop': False, 'archivepath': '', 'askmdn': '', 'certfile': '', 'charset': 'us-ascii', 'desc': 'Get file from environ variable $BOTS_FILE_IN', 'filename': '', 'ftpaccount': '', 'ftpactive': False, 'ftpbinary': False, 'host': '', 'idchannel': 'bots_file_in', 'inorout': 'in', 'keyfile': '', 'lockname': '', 'mdnchannel': '', 'parameters': '', 'path': '', 'port': 0, 'remove': False, 'rsrv1': '', 'rsrv2': None, 'rsrv3': None, 'secret': '', 'sendmdn': '', 'starttls': False, 'syslock': False, 'testpath': '', 'type': 'communicationscript', 'username': ''},
{'plugintype': 'channel', 'apop': False, 'archivepath': '', 'askmdn': '', 'certfile': '', 'charset': 'us-ascii', 'desc': 'Write file from environ variable $BOTS_FILE_OUT', 'filename': '', 'ftpaccount': '', 'ftpactive': False, 'ftpbinary': False, 'host': '', 'idchannel': 'bots_file_out', 'inorout': 'out', 'keyfile': '', 'lockname': '', 'mdnchannel': '', 'parameters': '', 'path': '', 'port': 0, 'remove': False, 'rsrv1': '', 'rsrv2': None, 'rsrv3': None, 'secret': '', 'sendmdn': '', 'starttls': False, 'syslock': False, 'testpath': '', 'type': 'communicationscript', 'username': ''},
{'plugintype': 'translate', 'active': True, 'alt': 'cii2creditnote', 'desc': 'D16B CII > UBL CreditNote', 'fromeditype': 'xml', 'frommessagetype': 'D16B_CII', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': 'xml', 'tomessagetype': 'UBL21_CreditNote', 'topartner': None, 'tscript': 'D16B_cii2xmlUBL21_invoice'},
{'plugintype': 'translate', 'active': True, 'alt': 'cii2ubl', 'desc': '', 'fromeditype': 'xml', 'frommessagetype': 'D16B_CII', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': 'xml', 'tomessagetype': 'UBL21_INVOICE', 'topartner': None, 'tscript': 'D16B_cii2xmlUBL21_invoice'},
{'plugintype': 'translate', 'active': True, 'alt': 'ubl2cii', 'desc': 'UBL CreditNote > D16B CII', 'fromeditype': 'xml', 'frommessagetype': 'UBL21_CreditNote', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': 'xml', 'tomessagetype': 'D16B_CII', 'topartner': None, 'tscript': 'UBL21_invoice2xmlD16B_cii'},
{'plugintype': 'translate', 'active': True, 'alt': 'ubl2cii', 'desc': '', 'fromeditype': 'xml', 'frommessagetype': 'UBL21_INVOICE', 'frompartner': None, 'rsrv1': None, 'rsrv2': None, 'toeditype': 'xml', 'tomessagetype': 'D16B_CII', 'topartner': None, 'tscript': 'UBL21_invoice2xmlD16B_cii'},
{'plugintype': 'routes', 'active': True, 'alt': 'cii2ubl', 'defer': False, 'desc': 'Translate CII D16B to Invoice UBL 2.1', 'fromchannel': 'bots_file_in', 'fromeditype': 'xml', 'frommessagetype': 'D16B_CII', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': 'CII_2_UBL', 'notindefaultrun': True, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': '', 'tochannel': 'bots_file_out', 'toeditype': '', 'tomessagetype': '', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
{'plugintype': 'routes', 'active': True, 'alt': 'ubl2cii', 'defer': False, 'desc': 'Translate Invoice UBL 2.1 to CII D16B', 'fromchannel': 'bots_file_in', 'fromeditype': 'xml', 'frommessagetype': 'UBL21_INVOICE', 'frompartner': None, 'frompartner_tochannel': None, 'idroute': 'UBL_2_CII', 'notindefaultrun': True, 'rsrv1': None, 'rsrv2': None, 'seq': 1, 'testindicator': '', 'tochannel': 'bots_file_out', 'toeditype': '', 'tomessagetype': '', 'topartner': None, 'topartner_tochannel': None, 'translateind': 1, 'zip_incoming': None, 'zip_outgoing': None},
]
